### ISSUE TITLE
gradient-convert --help broken

### ISSUE THREAD

**Issue by jjgreen** [jjgreen/cptutils#13]
It should list the conversions available but errors:
```
supported formats:
Traceback (most recent call last):
  File "/usr/local/bin/gradient-convert", line 580, in <module>
    main()
  File "/usr/local/bin/gradient-convert", line 493, in main
    formats_supported(gajmat, gnames)
  File "/usr/local/bin/gradient-convert", line 130, in formats_supported
    "W" if wfmt[name] else "-"))
ValueError: Invalid conversion specification
```
Hurrah for testing ...

**Comment by jjgreen** [comment]
Fixed in the [gradient-convert-tests branch](https://github.com/jjgreen/cptutils/tree/gradient-convert-tests)
